# Generated by Django 2.1 on 2018-10-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181007_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='userName',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usermsg',
            old_name='userName',
            new_name='user',
        ),
    ]
