# Generated by Django 2.1 on 2018-10-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_comment_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.userInfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='like_comment',
            field=models.ManyToManyField(through='repository.UserComment', to='repository.Comment'),
        ),
    ]
