# Generated by Django 2.1 on 2018-10-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20181009_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/static/image/HP.jpg', null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='nameless', max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
