# Generated by Django 2.1 on 2018-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20181023_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='presentation',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='个人说明'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/media/avatar/HP.jpg', null=True, upload_to='', verbose_name='头像'),
        ),
    ]
