# Generated by Django 2.1 on 2018-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20181027_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/media/avatar/HP.jpg', height_field='url_height', upload_to='media/avatar', verbose_name='头像', width_field='url_width'),
        ),
    ]
