# Generated by Django 2.1 on 2018-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20181027_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/media/avatar/HP.jpg', upload_to='media/avatar', verbose_name='头像'),
        ),
    ]
